# Use the official Python image as base
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory in the container
WORKDIR /app


# Install Python dependencies
COPY requirements.txt /app/
RUN pip install  -r requirements.txt

# Copy the application code into the container
COPY . /app/

# Expose the port on which the FastAPI app will run
EXPOSE 8090

# Command to run the FastAPI app
CMD ["python","app.py"]